--- 
apiVersion: ocs.openshift.io/v1
kind: StorageCluster
metadata: 
  name: ocs-storagecluster
  namespace: openshift-storage
spec: 
  manageNodes: false
  monPVCTemplate: 
    spec: 
      accessModes: 
        - ReadWriteOnce
      resources: 
        requests: 
          storage: 10Gi
      storageClassName: gp2  #  <-- This should be changed as per platform
      volumeMode: Filesystem
  storageDeviceSets: 
    - count: 1
      dataPVCTemplate: 
        spec: 
          accessModes: 
            - ReadWriteOnce
          resources: 
            requests: 
              storage: 0.5Ti    # <--- Supported sizes are 0.5, 2, 4 Ti
          storageClassName: gp2   #  <-- This should be changed as per platform
          volumeMode: Block
      name: ocs-deviceset
      placement: {}
      portable: true
      replica: 3
      resources: {}
