apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt
spec:
  acme:
    email: jason@kincl.dev
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: letsencrypt-account-key
    solvers:
    - dns01:
        route53:
          hostedZoneID: Z06685503SLODZT856H5B
          region: us-east2
          secretAccessKeySecretRef:
            name: cloud-credentials
            key: aws_secret_access_key
          accessKeyIDSecretRef:
            name: cloud-credentials
            key: aws_access_key_id
